# Generated by Django 6.0.2 on 2026-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_admin', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=200)),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=300)),
                ('feature_3', models.CharField(blank=True, max_length=300)),
                ('feature_4', models.CharField(blank=True, max_length=300)),
                ('feature_5', models.CharField(blank=True, max_length=300)),
                ('feature_6', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
