# Generated by Django 6.0.2 on 2026-02-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/%Y/%d')),
                ('discription', models.TextField()),
                ('live_link', models.URLField(blank=True)),
            ],
        ),
    ]
